name: Process Grades

on:
  push:
    paths:
      - "notlar.txt"
      - "grade_calculator.py"
      - "test_grade_calculator.py"

jobs:
  process_grades:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run tests
      run: |
        python -m unittest test_grade_calculator.py
    - name: Run grade processor
      run: |
        python grade_calculator.py
    - name: Show results
      run: |
        cat sonuclar.txt

    - name: Commit and Push results to degerlendirme branch
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch origin
        git checkout degerlendirme || git checkout -b degerlendirme origin/degerlendirme  # Branch'i oluştur veya geçiş yap
        git add sonuclar.txt
        git commit -m "Update sonuclar.txt after tests"
        git push origin degerlendirme
